#ifndef PDCM_CONFIG_S32K358_H
#define PDCM_CONFIG_S32K358_H

#include <stdint.h>

// ============================================================================
// S32K358 HDQFP-172 Pin Allocation -- Auto-generated 2026-03-13
// ============================================================================
//
// NXP S32K358: Dual Cortex-M7 @ 240MHz, 172-pin HDQFP
// ~142 I/O pins, 5 GPIO ports (PTA-PTE), 3x SAR ADC, 3x eMIOS, 6x CAN FD
//
// SIUL2 MSCR index = port * 32 + pin_number
//   PTA0..31 = MSCR[0..31]     PTB0..31 = MSCR[32..63]
//   PTC0..31 = MSCR[64..95]    PTD0..31 = MSCR[96..127]
//   PTE0..31 = MSCR[128..159]
//
// Pin budget (120 assigned):
//    14 PWM outputs       -- eMIOS1 channels -> TC4427A / DRV8876
//    34 gate driver GPIO  -- push-pull outputs -> TC4427A
//     2 H-bridge control  -- GPIO (nSLEEP, nFAULT)
//    15 switch inputs     -- GPIO input w/ external pull-up
//    49 ADC inputs        -- 46 current sense + 3 sensor (direct, no MUX)
//     2 CAN FD            -- CAN0 TX/RX
//     4 JTAG              -- TMS, TCK, TDI, TDO
//     2 crystal            -- EXTAL (pad 23) / XTAL (pad 25) [dedicated, not GPIO]
//   ~30 power/ground       -- VDD, VSS, VDDA, etc.
//
// Source: NXP S32K358 IOMUX spreadsheet (S32K358_IOMUX.xlsx)
// Generated by: s32k358_pin_allocator.py
// ============================================================================

// --- Port/pin encoding helpers ---
// SIUL2 MSCR index = port_base + pin_number
#define PIN_PTA(n)  ((0u * 32u) + (n))
#define PIN_PTB(n)  ((1u * 32u) + (n))
#define PIN_PTC(n)  ((2u * 32u) + (n))
#define PIN_PTD(n)  ((3u * 32u) + (n))
#define PIN_PTE(n)  ((4u * 32u) + (n))

// ============================================================================
// JTAG / Debug (fixed pins -- do not reassign)
// ============================================================================

namespace JtagPin {
    constexpr uint8_t TCK          = PIN_PTC(4);    // PTC4 pad 166 -- JTAG_TCK
    constexpr uint8_t TDI          = PIN_PTC(5);    // PTC5 pad 165 -- JTAG_TDI
    constexpr uint8_t TDO          = PIN_PTA(10);    // PTA10 pad 161 -- JTAG_TDO
    constexpr uint8_t TMS          = PIN_PTA(4);    // PTA4 pad 170 -- JTAG_TMS
    // nRESET is a dedicated pin (not GPIO-muxed)
}

// ============================================================================
// CAN FD 0 -- Vehicle bus (PTC3/PTC2, pads 49/50)
// ============================================================================

namespace CanPin {
    constexpr uint8_t CAN0_TX      = PIN_PTC(3);    // PTC3 pad 49 -- FLEXCAN0 ALT3
    constexpr uint8_t CAN0_RX      = PIN_PTC(2);    // PTC2 pad 50 -- FLEXCAN0 IMCR
}

// ============================================================================
// PWM Outputs -- eMIOS1 (all 14 PWM channels on one timer instance)
// ============================================================================
// Single eMIOS instance keeps PWM timebase synchronized across all channels.
// Each pin: MSCR ALT mode selects eMIOS_1 function.
//
//  Signal            Pin     Pad   eMIOS1_CH   ALT
//  ----------------  ------  ----  ----------  ----
//  FAN_1             PTC12      83  CH[ 2]_H   ALT2
//  FAN_2             PTC13      81  CH[ 3]_H   ALT2
//  BLOWER            PTC14      71  CH[ 4]_H   ALT5
//  LOW_BEAM_L        PTE12      29  CH[ 5]_H   ALT4
//  LOW_BEAM_R        PTC28      96  CH[ 7]_H   ALT2
//  HIGH_BEAM_L       PTC16      66  CH[ 9]_H   ALT2
//  HIGH_BEAM_R       PTB4       48  CH[10]_H   ALT6
//  DRL               PTA28      30  CH[11]_H   ALT2
//  INTERIOR          PTA29      32  CH[12]_H   ALT2
//  COURTESY          PTD15      35  CH[14]_H   ALT3
//  SEAT_HEATER_L     PTD16      34  CH[15]_H   ALT5
//  SEAT_HEATER_R     PTB20      44  CH[16]_X   ALT2
//  HBRIDGE_IN1       PTB21      45  CH[17]_Y   ALT2
//  HBRIDGE_IN2       PTB22      67  CH[18]_Y   ALT2

namespace Pin {

    // --- PWM-capable gate driver outputs (eMIOS1) ---
    constexpr uint8_t CH_FAN_1             = PIN_PTC(12);  // pad  83 -- eMIOS1_CH[2] PWM
    constexpr uint8_t CH_FAN_2             = PIN_PTC(13);  // pad  81 -- eMIOS1_CH[3] PWM
    constexpr uint8_t CH_BLOWER            = PIN_PTC(14);  // pad  71 -- eMIOS1_CH[4] PWM
    constexpr uint8_t CH_LOW_BEAM_L        = PIN_PTE(12);  // pad  29 -- eMIOS1_CH[5] PWM
    constexpr uint8_t CH_LOW_BEAM_R        = PIN_PTC(28);  // pad  96 -- eMIOS1_CH[7] PWM
    constexpr uint8_t CH_HIGH_BEAM_L       = PIN_PTC(16);  // pad  66 -- eMIOS1_CH[9] PWM
    constexpr uint8_t CH_HIGH_BEAM_R       = PIN_PTB( 4);  // pad  48 -- eMIOS1_CH[10] PWM
    constexpr uint8_t CH_DRL               = PIN_PTA(28);  // pad  30 -- eMIOS1_CH[11] PWM
    constexpr uint8_t CH_INTERIOR          = PIN_PTA(29);  // pad  32 -- eMIOS1_CH[12] PWM
    constexpr uint8_t CH_COURTESY          = PIN_PTD(15);  // pad  35 -- eMIOS1_CH[14] PWM
    constexpr uint8_t CH_SEAT_HEATER_L     = PIN_PTD(16);  // pad  34 -- eMIOS1_CH[15] PWM
    constexpr uint8_t CH_SEAT_HEATER_R     = PIN_PTB(20);  // pad  44 -- eMIOS1_CH[16] PWM

    // --- Non-PWM gate driver outputs (GPIO push-pull) ---
    // Tier 1
    constexpr uint8_t CH_FUEL_PUMP         = PIN_PTC( 1);  // pad  61 -- GPIO out
    constexpr uint8_t CH_AC_CLUTCH         = PIN_PTC( 0);  // pad  62 -- GPIO out
    constexpr uint8_t CH_TURN_L            = PIN_PTD( 9);  // pad  63 -- GPIO out
    constexpr uint8_t CH_TURN_R            = PIN_PTD( 8);  // pad  64 -- GPIO out
    constexpr uint8_t CH_BRAKE_L           = PIN_PTC(17);  // pad  65 -- GPIO out
    constexpr uint8_t CH_BRAKE_R           = PIN_PTC(15);  // pad  68 -- GPIO out
    constexpr uint8_t CH_REVERSE           = PIN_PTB(23);  // pad  69 -- GPIO out
    constexpr uint8_t CH_HORN              = PIN_PTB(24);  // pad  70 -- GPIO out
    constexpr uint8_t CH_WIPER             = PIN_PTB(25);  // pad  72 -- GPIO out
    constexpr uint8_t CH_ACCESSORY         = PIN_PTB(26);  // pad  73 -- GPIO out
    constexpr uint8_t CH_FRONT_AXLE        = PIN_PTB( 3);  // pad  74 -- GPIO out
    constexpr uint8_t CH_LIGHT_BAR         = PIN_PTB(27);  // pad  75 -- GPIO out
    // Tier 2 -- Enable signals
    constexpr uint8_t CH_AMP_REMOTE_1      = PIN_PTB(28);  // pad  76 -- GPIO out
    constexpr uint8_t CH_AMP_REMOTE_2      = PIN_PTB(29);  // pad  80 -- GPIO out
    constexpr uint8_t CH_HEADUNIT_EN       = PIN_PTC(18);  // pad  82 -- GPIO out
    // Tier 3 -- Cameras, modules, exterior
    constexpr uint8_t CH_CAM_FRONT         = PIN_PTC(19);  // pad  84 -- GPIO out
    constexpr uint8_t CH_CAM_REAR          = PIN_PTC(20);  // pad  85 -- GPIO out
    constexpr uint8_t CH_CAM_SIDE          = PIN_PTC(21);  // pad  86 -- GPIO out
    constexpr uint8_t CH_PARK_SENS         = PIN_PTC(27);  // pad  93 -- GPIO out
    constexpr uint8_t CH_RADAR_BSM         = PIN_PTC(29);  // pad  99 -- GPIO out
    constexpr uint8_t CH_GCM_POWER         = PIN_PTC(30);  // pad 101 -- GPIO out
    constexpr uint8_t CH_GPS_CELL          = PIN_PTA( 5);  // pad 167 -- GPIO out
    constexpr uint8_t CH_DASH_CAM          = PIN_PTA(18);  // pad   1 -- GPIO out
    constexpr uint8_t CH_FUTURE_MOD        = PIN_PTA(19);  // pad   2 -- GPIO out
    constexpr uint8_t CH_ROCK_LIGHTS       = PIN_PTA(20);  // pad   3 -- GPIO out
    constexpr uint8_t CH_BED_LIGHTS        = PIN_PTE(16);  // pad   4 -- GPIO out
    constexpr uint8_t CH_PUDDLE_LIGHTS     = PIN_PTE(15);  // pad   5 -- GPIO out
    constexpr uint8_t CH_FUTURE_EXT        = PIN_PTA(21);  // pad   6 -- GPIO out
    // Expansion
    constexpr uint8_t CH_EXPANSION_1       = PIN_PTD( 1);  // pad   7 -- GPIO out
    constexpr uint8_t CH_EXPANSION_2       = PIN_PTD( 0);  // pad   8 -- GPIO out
    constexpr uint8_t CH_EXPANSION_3       = PIN_PTE(11);  // pad   9 -- GPIO out
    constexpr uint8_t CH_EXPANSION_4       = PIN_PTE(10);  // pad  10 -- GPIO out
    constexpr uint8_t CH_EXPANSION_5       = PIN_PTE(13);  // pad  11 -- GPIO out
    constexpr uint8_t CH_EXPANSION_6       = PIN_PTE( 5);  // pad  12 -- GPIO out

    // --- H-Bridge (DRV8876) for 4WD encoder motor ---
    constexpr uint8_t HBRIDGE_IN1          = PIN_PTB(21);  // pad  45 -- eMIOS1_CH[17] PWM
    constexpr uint8_t HBRIDGE_IN2          = PIN_PTB(22);  // pad  67 -- eMIOS1_CH[18] PWM
    constexpr uint8_t HBRIDGE_NSLEEP       = PIN_PTD(17);  // pad  31 -- GPIO output
    constexpr uint8_t HBRIDGE_NFAULT       = PIN_PTA(24);  // pad  14 -- GPIO input

    // --- Safety-Critical Switch Inputs (direct GPIO -- never behind SPI/I2C) ---
    constexpr uint8_t BRAKE_SWITCH_1    = PIN_PTA(30);  // pad  33 -- Factory brake switch
    constexpr uint8_t BRAKE_SWITCH_2    = PIN_PTA(31);  // pad  39 -- Dedicated brake switch
}

// ============================================================================
// Switch Inputs -- 15 direct GPIO inputs
// ============================================================================
// External pull-up + TVS + series R + RC filter on each input.
// Brake switches are duplicated in Pin:: namespace above for clarity.

namespace SwitchPin {
    constexpr uint8_t TURN_L           = PIN_PTA(25);  // pad  15
    constexpr uint8_t TURN_R           = PIN_PTD(14);  // pad  40
    constexpr uint8_t HIGH_BEAM        = PIN_PTD(13);  // pad  41
    constexpr uint8_t FLASH_PASS       = PIN_PTB(18);  // pad  42
    constexpr uint8_t HAZARD           = PIN_PTB(19);  // pad  43
    constexpr uint8_t HORN             = PIN_PTE( 8);  // pad  46
    constexpr uint8_t REVERSE          = PIN_PTB( 5);  // pad  47
    constexpr uint8_t AC_REQ           = PIN_PTD( 7);  // pad  51
    constexpr uint8_t WIPER_INT        = PIN_PTD( 6);  // pad  52
    constexpr uint8_t WIPER_LO         = PIN_PTD( 5);  // pad  53
    constexpr uint8_t WIPER_HI         = PIN_PTD(12);  // pad  54
    constexpr uint8_t WASHER           = PIN_PTD(11);  // pad  55
    constexpr uint8_t BRAKE_SW1        = PIN_PTA(30);  // pad  33
    constexpr uint8_t BRAKE_SW2        = PIN_PTA(31);  // pad  39
    constexpr uint8_t START_BTN        = PIN_PTD(10);  // pad  56

    constexpr uint8_t NUM_SWITCHES      = 15;
}

// ============================================================================
// eMIOS Configuration -- PWM timer instance + channel mapping
// ============================================================================
// All PWM outputs on eMIOS1 instance. Same timebase = synchronized duty cycles.

namespace EmiosCfg {
    constexpr uint8_t INSTANCE          = 1;    // eMIOS1

    // Gate driver PWM channels (maps to eMIOS1 channel numbers)
    constexpr uint8_t CH_FAN_1             =  2;   // eMIOS1_CH[2]
    constexpr uint8_t CH_FAN_2             =  3;   // eMIOS1_CH[3]
    constexpr uint8_t CH_BLOWER            =  4;   // eMIOS1_CH[4]
    constexpr uint8_t CH_LOW_BEAM_L        =  5;   // eMIOS1_CH[5]
    constexpr uint8_t CH_LOW_BEAM_R        =  7;   // eMIOS1_CH[7]
    constexpr uint8_t CH_HIGH_BEAM_L       =  9;   // eMIOS1_CH[9]
    constexpr uint8_t CH_HIGH_BEAM_R       = 10;   // eMIOS1_CH[10]
    constexpr uint8_t CH_DRL               = 11;   // eMIOS1_CH[11]
    constexpr uint8_t CH_INTERIOR          = 12;   // eMIOS1_CH[12]
    constexpr uint8_t CH_COURTESY          = 14;   // eMIOS1_CH[14]
    constexpr uint8_t CH_SEAT_HEATER_L     = 15;   // eMIOS1_CH[15]
    constexpr uint8_t CH_SEAT_HEATER_R     = 16;   // eMIOS1_CH[16]

    // H-bridge PWM channels
    constexpr uint8_t CH_HBRIDGE_IN1       = 17;   // eMIOS1_CH[17]
    constexpr uint8_t CH_HBRIDGE_IN2       = 18;   // eMIOS1_CH[18]

    constexpr uint8_t NUM_PWM_CHANNELS  = 12;
}

// ============================================================================
// ADC Configuration -- 3x SAR ADC instances, direct (no MUX)
// ============================================================================
//
// S32K358 has 3 SAR ADC instances (ADC0, ADC1, ADC2).
// Each INA180A1 output connects directly to an MCU ADC pin -- no analog MUX.
// ADC analog inputs bypass SIUL2 digital mux (hardwired analog paths).
//
// Pin-to-ADC mapping extracted from S32K358_IOMUX.xlsx PeripheralSummaries.
// ============================================================================

// ADC identifier: encodes instance + channel in one byte
// Upper 2 bits = ADC instance (0-2), lower 6 bits = channel number (0-63)
#define ADC_ID(instance, channel) (((instance) << 6) | ((channel) & 0x3F))
#define ADC_INSTANCE(id)          ((id) >> 6)
#define ADC_CHANNEL(id)           ((id) & 0x3F)

namespace AdcCurrentSense {
    // Per-channel current sense ADC assignments
    // Index = OutputChannel enum value (0-46, skip 24=H-bridge)
    // Value = ADC_ID(instance, channel)
    constexpr uint8_t NUM_CHANNELS = 46;

    constexpr uint8_t CSENSE[47] = {
        ADC_ID(2,  9),                // ch  0: FUEL_PUMP        -- PTE4 pad  13 (ADC2_S9)
        ADC_ID(2, 23),                // ch  1: FAN_1            -- PTC23 pad  87 (ADC2_S23)
        ADC_ID(2, 22),                // ch  2: FAN_2            -- PTC24 pad  88 (ADC2_S22)
        ADC_ID(0, 20),                // ch  3: BLOWER           -- PTC25 pad  89 (ADC0_S20)
        ADC_ID(0, 17),                // ch  4: AC_CLUTCH        -- PTC11 pad  90 (ADC0_S17)
        ADC_ID(0, 21),                // ch  5: LOW_BEAM_L       -- PTC26 pad  91 (ADC0_S21)
        ADC_ID(1,  3),                // ch  6: LOW_BEAM_R       -- PTC10 pad  92 (ADC1_X[3])
        ADC_ID(0, 15),                // ch  7: HIGH_BEAM_L      -- PTB1 pad  94 (ADC0_S15)
        ADC_ID(0, 14),                // ch  8: HIGH_BEAM_R      -- PTB0 pad  95 (ADC0_S14)
        ADC_ID(0, 13),                // ch  9: TURN_L           -- PTC9 pad  97 (ADC0_S13)
        ADC_ID(0, 12),                // ch 10: TURN_R           -- PTC8 pad  98 (ADC0_S12)
        ADC_ID(0, 11),                // ch 11: BRAKE_L          -- PTA7 pad 100 (ADC0_S11)
        ADC_ID(0, 18),                // ch 12: BRAKE_R          -- PTA6 pad 102 (ADC0_S18)
        ADC_ID(2, 21),                // ch 13: REVERSE          -- PTC31 pad 103 (ADC2_S21)
        ADC_ID(2, 20),                // ch 14: DRL              -- PTE7 pad 104 (ADC2_S20)
        ADC_ID(2, 19),                // ch 15: INTERIOR         -- PTA17 pad 109 (ADC2_S19)
        ADC_ID(1,  2),                // ch 16: COURTESY         -- PTB17 pad 110 (ADC1_X[2])
        ADC_ID(0, 22),                // ch 17: HORN             -- PTD20 pad 111 (ADC0_S22)
        ADC_ID(1, 12),                // ch 18: WIPER            -- PTB16 pad 112 (ADC1_S12)
        ADC_ID(1, 11),                // ch 19: ACCESSORY        -- PTB15 pad 113 (ADC1_S11)
        ADC_ID(0,  9),                // ch 20: FRONT_AXLE       -- PTB14 pad 114 (ADC0_S9)
        ADC_ID(0, 23),                // ch 21: SEAT_HEATER_L    -- PTD21 pad 115 (ADC0_S23)
        ADC_ID(0,  8),                // ch 22: SEAT_HEATER_R    -- PTB13 pad 116 (ADC0_S8)
        ADC_ID(1,  1),                // ch 23: LIGHT_BAR        -- PTB12 pad 117 (ADC1_X[1])
        0,                              // ch 24: (H-bridge -- uses HB_CS_ADC)
        ADC_ID(2, 18),                // ch 25: AMP_REMOTE_1     -- PTD22 pad 118 (ADC2_S18)
        ADC_ID(0, 19),                // ch 26: AMP_REMOTE_2     -- PTD4 pad 119 (ADC0_S19)
        ADC_ID(0, 10),                // ch 27: HEADUNIT_EN      -- PTD3 pad 120 (ADC0_S10)
        ADC_ID(0, 16),                // ch 28: CAM_FRONT        -- PTD2 pad 121 (ADC0_S16)
        ADC_ID(2, 17),                // ch 29: CAM_REAR         -- PTD23 pad 122 (ADC2_S17)
        ADC_ID(1, 17),                // ch 30: CAM_SIDE         -- PTA3 pad 123 (ADC1_S17)
        ADC_ID(1,  0),                // ch 31: PARK_SENS        -- PTA2 pad 124 (ADC1_X[0])
        ADC_ID(1, 20),                // ch 32: RADAR_BSM        -- PTD24 pad 125 (ADC1_S20)
        ADC_ID(0,  3),                // ch 33: GCM_POWER        -- PTB11 pad 126 (ADC0_X[3])
        ADC_ID(0,  2),                // ch 34: GPS_CELL         -- PTB10 pad 129 (ADC0_X[2])
        ADC_ID(0,  1),                // ch 35: DASH_CAM         -- PTB9 pad 130 (ADC0_X[1])
        ADC_ID(2, 16),                // ch 36: FUTURE_MOD       -- PTD26 pad 131 (ADC2_S16)
        ADC_ID(1, 21),                // ch 37: ROCK_LIGHTS      -- PTD27 pad 132 (ADC1_S21)
        ADC_ID(0,  0),                // ch 38: BED_LIGHTS       -- PTB8 pad 133 (ADC0_X[0])
        ADC_ID(1, 22),                // ch 39: PUDDLE_LIGHTS    -- PTD28 pad 134 (ADC1_S22)
        ADC_ID(1, 23),                // ch 40: FUTURE_EXT       -- PTD29 pad 136 (ADC1_S23)
        ADC_ID(2, 15),                // ch 41: EXPANSION_1      -- PTD30 pad 138 (ADC2_S15)
        ADC_ID(2, 14),                // ch 42: EXPANSION_2      -- PTD31 pad 139 (ADC2_S14)
        ADC_ID(1, 16),                // ch 43: EXPANSION_3      -- PTC7 pad 140 (ADC1_S16)
        ADC_ID(1, 18),                // ch 44: EXPANSION_4      -- PTC6 pad 141 (ADC1_S18)
        ADC_ID(2, 10),                // ch 45: EXPANSION_5      -- PTE17 pad 142 (ADC2_S10)
        ADC_ID(1, 13)                 // ch 46: EXPANSION_6      -- PTA16 pad 143 (ADC1_S13)
    };
}

// --- Sensor ADC ---
namespace AdcSensor {
    constexpr uint8_t BATTERY      = ADC_ID(2, 11);  // PTE18 pad 144 (ADC2_S11) -- Battery voltage divider
    constexpr uint8_t FOURWD_POS   = ADC_ID(1,  7);  // PTA15 pad 145 (ADC1_P7) -- 4WD transfer case potentiometer
    constexpr uint8_t HB_CS        = ADC_ID(1,  6);  // PTE6 pad 146 (ADC1_P6) -- DRV8876 IPROPI current sense
}

// --- ADC Hardware Config ---
namespace AdcConfig {
    constexpr uint8_t  NUM_SAR_INSTANCES    = 3;     // ADC0, ADC1, ADC2
    constexpr uint16_t RESOLUTION           = 4096;  // 12-bit SAR
    constexpr uint16_t REF_MV               = 3300;  // 3.3V VDDA reference
    constexpr uint8_t  AMPLIFIER_GAIN       = 20;    // INA180A1 (gain = 20)
}

// --- ADC Pin-to-Pad Lookup (for schematic cross-reference) ---
// Maps ADC_ID -> physical pad number on HDQFP-172 package
namespace AdcPads {
    // ADC0: 20 channels used
    //   ADC0_X[0]    -> PTB8   pad 133
    //   ADC0_X[1]    -> PTB9   pad 130
    //   ADC0_X[2]    -> PTB10  pad 129
    //   ADC0_X[3]    -> PTB11  pad 126
    //   ADC0_S8      -> PTB13  pad 116
    //   ADC0_S9      -> PTB14  pad 114
    //   ADC0_S10     -> PTD3   pad 120
    //   ADC0_S11     -> PTA7   pad 100
    //   ADC0_S12     -> PTC8   pad  98
    //   ADC0_S13     -> PTC9   pad  97
    //   ADC0_S14     -> PTB0   pad  95
    //   ADC0_S15     -> PTB1   pad  94
    //   ADC0_S16     -> PTD2   pad 121
    //   ADC0_S17     -> PTC11  pad  90
    //   ADC0_S18     -> PTA6   pad 102
    //   ADC0_S19     -> PTD4   pad 119
    //   ADC0_S20     -> PTC25  pad  89
    //   ADC0_S21     -> PTC26  pad  91
    //   ADC0_S22     -> PTD20  pad 111
    //   ADC0_S23     -> PTD21  pad 115
    // ADC1: 16 channels used
    //   ADC1_X[0]    -> PTA2   pad 124
    //   ADC1_X[1]    -> PTB12  pad 117
    //   ADC1_X[2]    -> PTB17  pad 110
    //   ADC1_X[3]    -> PTC10  pad  92
    //   ADC1_P6      -> PTE6   pad 146
    //   ADC1_P7      -> PTA15  pad 145
    //   ADC1_S11     -> PTB15  pad 113
    //   ADC1_S12     -> PTB16  pad 112
    //   ADC1_S13     -> PTA16  pad 143
    //   ADC1_S16     -> PTC7   pad 140
    //   ADC1_S17     -> PTA3   pad 123
    //   ADC1_S18     -> PTC6   pad 141
    //   ADC1_S20     -> PTD24  pad 125
    //   ADC1_S21     -> PTD27  pad 132
    //   ADC1_S22     -> PTD28  pad 134
    //   ADC1_S23     -> PTD29  pad 136
    // ADC2: 13 channels used
    //   ADC2_S9      -> PTE4   pad  13
    //   ADC2_S10     -> PTE17  pad 142
    //   ADC2_S11     -> PTE18  pad 144
    //   ADC2_S14     -> PTD31  pad 139
    //   ADC2_S15     -> PTD30  pad 138
    //   ADC2_S16     -> PTD26  pad 131
    //   ADC2_S17     -> PTD23  pad 122
    //   ADC2_S18     -> PTD22  pad 118
    //   ADC2_S19     -> PTA17  pad 109
    //   ADC2_S20     -> PTE7   pad 104
    //   ADC2_S21     -> PTC31  pad 103
    //   ADC2_S22     -> PTC24  pad  88
    //   ADC2_S23     -> PTC23  pad  87
}

// ============================================================================
// Current Sense Configuration (S32K358-specific)
// ============================================================================
// No analog MUX -- all 46 INA180A1 outputs go directly to ADC pins.
// CurrentSense module reads all channels sequentially via SAR ADC scan mode.

namespace CurrentSense {
    constexpr uint8_t  NUM_CHANNELS         = 46;    // Direct ADC (no MUX)
    constexpr uint8_t  CHANNELS_PER_MUX     = 0;     // Not applicable
    constexpr uint8_t  NUM_MUX_ICS          = 0;     // Not applicable
    constexpr uint16_t ADC_RESOLUTION       = 4096;  // 12-bit
    constexpr uint16_t ADC_REF_MV           = 3300;  // 3.3V reference
    constexpr uint8_t  AMPLIFIER_GAIN       = 20;    // INA180A1 (gain 20)
}

// ============================================================================
// Battery Voltage Divider
// ============================================================================

namespace BatteryADC {
    constexpr uint16_t DIVIDER_R1_OHM       = 10000;  // R1 to +12V
    constexpr uint16_t DIVIDER_R2_OHM       = 3300;   // R2 to GND
    constexpr uint32_t DIVIDER_MULT_X1000   = 4030;   // (R1+R2)/R2 x 1000
}

// ============================================================================
// 4WD Position Potentiometer
// ============================================================================

namespace FourWDPosADC {
    constexpr uint16_t POS_2HI_MV           = 300;
    constexpr uint16_t POS_A4WD_MV          = 900;
    constexpr uint16_t POS_4HI_MV           = 1500;
    constexpr uint16_t POS_NEUTRAL_MV       = 2100;
    constexpr uint16_t POS_4LO_MV           = 2700;
    constexpr uint16_t POS_TOLERANCE_MV     = 200;
}

// ============================================================================
// Pin Allocation Summary
// ============================================================================
//
//  PTA:
//    PTA2   pad 124  ADC_CS_PARK_SENS  (ADC1_X[0])
//    PTA3   pad 123  ADC_CS_CAM_SIDE  (ADC1_S17)
//    PTA4   pad 170  JTAG_TMS  (JTAG)
//    PTA5   pad 167  GATE_GPS_CELL  (GPIO_OUT)
//    PTA6   pad 102  ADC_CS_BRAKE_R  (ADC0_S18)
//    PTA7   pad 100  ADC_CS_BRAKE_L  (ADC0_S11)
//    PTA10  pad 161  JTAG_TDO  (JTAG)
//    PTA15  pad 145  ADC_4WD_ADC  (ADC1_P7)
//    PTA16  pad 143  ADC_CS_EXPANSION_6  (ADC1_S13)
//    PTA17  pad 109  ADC_CS_INTERIOR  (ADC2_S19)
//    PTA18  pad   1  GATE_DASH_CAM  (GPIO_OUT)
//    PTA19  pad   2  GATE_FUTURE_MOD  (GPIO_OUT)
//    PTA20  pad   3  GATE_ROCK_LIGHTS  (GPIO_OUT)
//    PTA21  pad   6  GATE_FUTURE_EXT  (GPIO_OUT)
//    PTA24  pad  14  HBRIDGE_NFAULT  (GPIO_IN)
//    PTA25  pad  15  SW_TURN_L  (GPIO_IN)
//    PTA28  pad  30  PWM_DRL  (eMIOS_1_CH[11]_H)
//    PTA29  pad  32  PWM_INTERIOR  (eMIOS_1_CH[12]_H)
//    PTA30  pad  33  BRAKE_SW1  (GPIO_IN)
//    PTA31  pad  39  BRAKE_SW2  (GPIO_IN)
//  PTB:
//    PTB0   pad  95  ADC_CS_HIGH_BEAM_R  (ADC0_S14)
//    PTB1   pad  94  ADC_CS_HIGH_BEAM_L  (ADC0_S15)
//    PTB3   pad  74  GATE_FRONT_AXLE  (GPIO_OUT)
//    PTB4   pad  48  PWM_HIGH_BEAM_R  (eMIOS_1_CH[10]_H)
//    PTB5   pad  47  SW_REVERSE  (GPIO_IN)
//    PTB8   pad 133  ADC_CS_BED_LIGHTS  (ADC0_X[0])
//    PTB9   pad 130  ADC_CS_DASH_CAM  (ADC0_X[1])
//    PTB10  pad 129  ADC_CS_GPS_CELL  (ADC0_X[2])
//    PTB11  pad 126  ADC_CS_GCM_POWER  (ADC0_X[3])
//    PTB12  pad 117  ADC_CS_LIGHT_BAR  (ADC1_X[1])
//    PTB13  pad 116  ADC_CS_SEAT_HEATER_R  (ADC0_S8)
//    PTB14  pad 114  ADC_CS_FRONT_AXLE  (ADC0_S9)
//    PTB15  pad 113  ADC_CS_ACCESSORY  (ADC1_S11)
//    PTB16  pad 112  ADC_CS_WIPER  (ADC1_S12)
//    PTB17  pad 110  ADC_CS_COURTESY  (ADC1_X[2])
//    PTB18  pad  42  SW_FLASH_PASS  (GPIO_IN)
//    PTB19  pad  43  SW_HAZARD  (GPIO_IN)
//    PTB20  pad  44  PWM_SEAT_HEATER_R  (eMIOS_1_CH[16]_X)
//    PTB21  pad  45  PWM_HBRIDGE_IN1  (eMIOS_1_CH[17]_Y)
//    PTB22  pad  67  PWM_HBRIDGE_IN2  (eMIOS_1_CH[18]_Y)
//    PTB23  pad  69  GATE_REVERSE  (GPIO_OUT)
//    PTB24  pad  70  GATE_HORN  (GPIO_OUT)
//    PTB25  pad  72  GATE_WIPER  (GPIO_OUT)
//    PTB26  pad  73  GATE_ACCESSORY  (GPIO_OUT)
//    PTB27  pad  75  GATE_LIGHT_BAR  (GPIO_OUT)
//    PTB28  pad  76  GATE_AMP_REMOTE_1  (GPIO_OUT)
//    PTB29  pad  80  GATE_AMP_REMOTE_2  (GPIO_OUT)
//  PTC:
//    PTC0   pad  62  GATE_AC_CLUTCH  (GPIO_OUT)
//    PTC1   pad  61  GATE_FUEL_PUMP  (GPIO_OUT)
//    PTC2   pad  50  CAN0_RX  (CAN0_RX)
//    PTC3   pad  49  CAN0_TX  (CAN0_TX)
//    PTC4   pad 166  JTAG_TCK  (JTAG)
//    PTC5   pad 165  JTAG_TDI  (JTAG)
//    PTC6   pad 141  ADC_CS_EXPANSION_4  (ADC1_S18)
//    PTC7   pad 140  ADC_CS_EXPANSION_3  (ADC1_S16)
//    PTC8   pad  98  ADC_CS_TURN_R  (ADC0_S12)
//    PTC9   pad  97  ADC_CS_TURN_L  (ADC0_S13)
//    PTC10  pad  92  ADC_CS_LOW_BEAM_R  (ADC1_X[3])
//    PTC11  pad  90  ADC_CS_AC_CLUTCH  (ADC0_S17)
//    PTC12  pad  83  PWM_FAN_1  (eMIOS_1_CH[2]_H)
//    PTC13  pad  81  PWM_FAN_2  (eMIOS_1_CH[3]_H)
//    PTC14  pad  71  PWM_BLOWER  (eMIOS_1_CH[4]_H)
//    PTC15  pad  68  GATE_BRAKE_R  (GPIO_OUT)
//    PTC16  pad  66  PWM_HIGH_BEAM_L  (eMIOS_1_CH[9]_H)
//    PTC17  pad  65  GATE_BRAKE_L  (GPIO_OUT)
//    PTC18  pad  82  GATE_HEADUNIT_EN  (GPIO_OUT)
//    PTC19  pad  84  GATE_CAM_FRONT  (GPIO_OUT)
//    PTC20  pad  85  GATE_CAM_REAR  (GPIO_OUT)
//    PTC21  pad  86  GATE_CAM_SIDE  (GPIO_OUT)
//    PTC23  pad  87  ADC_CS_FAN_1  (ADC2_S23)
//    PTC24  pad  88  ADC_CS_FAN_2  (ADC2_S22)
//    PTC25  pad  89  ADC_CS_BLOWER  (ADC0_S20)
//    PTC26  pad  91  ADC_CS_LOW_BEAM_L  (ADC0_S21)
//    PTC27  pad  93  GATE_PARK_SENS  (GPIO_OUT)
//    PTC28  pad  96  PWM_LOW_BEAM_R  (eMIOS_1_CH[7]_H)
//    PTC29  pad  99  GATE_RADAR_BSM  (GPIO_OUT)
//    PTC30  pad 101  GATE_GCM_POWER  (GPIO_OUT)
//    PTC31  pad 103  ADC_CS_REVERSE  (ADC2_S21)
//  PTD:
//    PTD0   pad   8  GATE_EXPANSION_2  (GPIO_OUT)
//    PTD1   pad   7  GATE_EXPANSION_1  (GPIO_OUT)
//    PTD2   pad 121  ADC_CS_CAM_FRONT  (ADC0_S16)
//    PTD3   pad 120  ADC_CS_HEADUNIT_EN  (ADC0_S10)
//    PTD4   pad 119  ADC_CS_AMP_REMOTE_2  (ADC0_S19)
//    PTD5   pad  53  SW_WIPER_LO  (GPIO_IN)
//    PTD6   pad  52  SW_WIPER_INT  (GPIO_IN)
//    PTD7   pad  51  SW_AC_REQ  (GPIO_IN)
//    PTD8   pad  64  GATE_TURN_R  (GPIO_OUT)
//    PTD9   pad  63  GATE_TURN_L  (GPIO_OUT)
//    PTD10  pad  56  SW_START_BTN  (GPIO_IN)
//    PTD11  pad  55  SW_WASHER  (GPIO_IN)
//    PTD12  pad  54  SW_WIPER_HI  (GPIO_IN)
//    PTD13  pad  41  SW_HIGH_BEAM  (GPIO_IN)
//    PTD14  pad  40  SW_TURN_R  (GPIO_IN)
//    PTD15  pad  35  PWM_COURTESY  (eMIOS_1_CH[14]_H)
//    PTD16  pad  34  PWM_SEAT_HEATER_L  (eMIOS_1_CH[15]_H)
//    PTD17  pad  31  HBRIDGE_NSLEEP  (GPIO_OUT)
//    PTD20  pad 111  ADC_CS_HORN  (ADC0_S22)
//    PTD21  pad 115  ADC_CS_SEAT_HEATER_L  (ADC0_S23)
//    PTD22  pad 118  ADC_CS_AMP_REMOTE_1  (ADC2_S18)
//    PTD23  pad 122  ADC_CS_CAM_REAR  (ADC2_S17)
//    PTD24  pad 125  ADC_CS_RADAR_BSM  (ADC1_S20)
//    PTD26  pad 131  ADC_CS_FUTURE_MOD  (ADC2_S16)
//    PTD27  pad 132  ADC_CS_ROCK_LIGHTS  (ADC1_S21)
//    PTD28  pad 134  ADC_CS_PUDDLE_LIGHTS  (ADC1_S22)
//    PTD29  pad 136  ADC_CS_FUTURE_EXT  (ADC1_S23)
//    PTD30  pad 138  ADC_CS_EXPANSION_1  (ADC2_S15)
//    PTD31  pad 139  ADC_CS_EXPANSION_2  (ADC2_S14)
//  PTE:
//    PTE4   pad  13  ADC_CS_FUEL_PUMP  (ADC2_S9)
//    PTE5   pad  12  GATE_EXPANSION_6  (GPIO_OUT)
//    PTE6   pad 146  ADC_HB_CS_ADC  (ADC1_P6)
//    PTE7   pad 104  ADC_CS_DRL  (ADC2_S20)
//    PTE8   pad  46  SW_HORN  (GPIO_IN)
//    PTE10  pad  10  GATE_EXPANSION_4  (GPIO_OUT)
//    PTE11  pad   9  GATE_EXPANSION_3  (GPIO_OUT)
//    PTE12  pad  29  PWM_LOW_BEAM_L  (eMIOS_1_CH[5]_H)
//    PTE13  pad  11  GATE_EXPANSION_5  (GPIO_OUT)
//    PTE15  pad   5  GATE_PUDDLE_LIGHTS  (GPIO_OUT)
//    PTE16  pad   4  GATE_BED_LIGHTS  (GPIO_OUT)
//    PTE17  pad 142  ADC_CS_EXPANSION_5  (ADC2_S10)
//    PTE18  pad 144  ADC_BATT_ADC  (ADC2_S11)
//
//  Total assigned: 120 pins
//    PWM outputs:     14
//    Gate driver GPIO: 34
//    H-bridge ctrl:   2
//    Switch inputs:   15
//    ADC inputs:      49
//    CAN:             2
//    JTAG:            4
//    Unassigned:      17 pins
//
// ============================================================================

#endif // PDCM_CONFIG_S32K358_H
